config/routes.rb
Rails.application.routes.draw do
  post '/graphql', to: 'graphql#execute'
  devise_for :users

  root to: 'view#show'

  if Rails.env.development?
    post '/schema', to: 'graphql_schema#execute'
    get '/graphiql', to: 'graphiql#show'
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  get '*path' => 'view#show',
      :constraints => lambda { |req| req.path.exclude? 'rails/active_storage' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/firebase_user.rb
# == Schema Information
#
# Table name: firebase_users
#
#  id         :uuid             not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  project_id :string           not null
#
class FirebaseUser < ApplicationRecord
end

app/models/forms/message.rb
class Forms::Message
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :id, :string
  attribute :text, :string

  validates :text, presence: true

  def valid!
    raise ActiveRecord::RecordInvalid, self if invalid?
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :uuid             not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_sentry_context if ENV['SENTRY_DSN'].present?

  def set_sentry_context
    if user_signed_in?
      Sentry.set_user(id: current_user.id, email: current_user.email)
    end
    Sentry.set_extras(params: params.to_unsafe_h, url: request.url)
  end
end

app/controllers/concerns/firebase_authorizable.rb
require 'net/http'
require 'uri'

module FirebaseAuthorizable
  extend ActiveSupport::Concern

  def set_sentry_context
    if firebase_user_signed_in?
      Sentry.set_user(id: current_firebase_user.id)
    end
    Sentry.set_extras(params: params.to_unsafe_h, url: request.url)
  end

  private

  def http_token
    if request.headers['Authorization'].present?
      request.headers['Authorization'].split(' ').last
    end
  end

  def auth_token
    verify = ENV['ID_ISSUER'].present?
    options = verify ? {
      algorithm: 'RS256',
      iss: ENV.fetch('ID_ISSUER'),
      verify_iss: true,
      aud: ENV.fetch('ID_API_AUDIENCE'),
      verify_aud: true,
    } : {}
    @auth_token ||= JWT.decode(http_token, nil, verify, options) do |header|
      jwks_raw = Net::HTTP.get URI(ENV.fetch('ID_JWKS_URL'))
      jwks_hash = JSON.parse(jwks_raw)
      signing_input = jwks_hash[header['kid']]
      cert = OpenSSL::X509::Certificate.new(signing_input)
      cert.public_key
    end
  rescue JWT::VerificationError, JWT::DecodeError
    [{}]
  end

  def current_firebase_user
    return nil if firebase_user_params.blank?
    @current_firebase_user ||= FirebaseUser.find_or_create_by(id: firebase_user_params[:sub], issuer: firebase_user_params[:iss])
  end

  def firebase_user_signed_in?
    current_firebase_user.present?
  end

  def firebase_user_params
    ActionController::Parameters.new(auth_token.first).permit(:sub, :iss, :email).to_h.compact
  end
end

app/controllers/graphiql_controller.rb
class GraphiqlController < ApplicationController
  layout false

  def show
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      user_signed_in: user_signed_in?,
      current_user: current_user,
    }
    result = AppSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/graphql_schema_controller.rb
class GraphqlSchemaController < ApplicationController
  skip_before_action :verify_authenticity_token

  def execute
    query = params[:query]
    operation_name = params[:operationName]
    result = AppSchema.execute(query, variables: {}, context: {}, operation_name: operation_name)
    render json: result
  end
end

app/controllers/view_controller.rb
class ViewController < ApplicationController
  layout false

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/graphiql/show.html.erb
<!--
 *  Copyright (c) 2019 GraphQL Contributors
 *  All rights reserved.
 *
 *  This source code is licensed under the license found in the
 *  LICENSE file in the root directory of this source tree.
-->
<!DOCTYPE html>
<html>
  <head>
    <style>
      body {
        height: 100%;
        margin: 0;
        width: 100%;
        overflow: hidden;
      }

      #graphiql {
        height: 100vh;
      }
    </style>

    <!--
      This GraphiQL example depends on Promise and fetch, which are available in
      modern browsers, but can be "polyfilled" for older browsers.
      GraphiQL itself depends on React DOM.
      If you do not want to rely on a CDN, you can host these files locally or
      include them directly in your favored resource bunder.
    -->
    <script
      crossorigin
      src="https://unpkg.com/react@16/umd/react.development.js"
    ></script>
    <script
      crossorigin
      src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"
    ></script>

    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>

    <!--
      These two files can be found in the npm module, however you may wish to
      copy them directly into your environment, or perhaps include them in your
      favored resource bundler.
     -->
    <link rel="stylesheet" href="https://unpkg.com/graphiql/graphiql.min.css" />
  </head>

  <body>
    <div id="graphiql">Loading...</div>
    <script
      src="https://unpkg.com/graphiql/graphiql.min.js"
      type="application/javascript"
    ></script>
    <script>
      function graphQLFetcher(graphQLParams) {
        return fetch(
          '<%= graphql_path %>',
          {
            method: 'post',
            headers: {
              Accept: 'application/json',
              'Content-Type': 'application/json',
              'X-CSRF-Token': Rails.csrfToken(),
            },
            body: JSON.stringify(graphQLParams),
            credentials: 'same-origin',
          },
        ).then(function (response) {
          return response.json().catch(function () {
            return response.text();
          });
        });
      }

      ReactDOM.render(
        React.createElement(GraphiQL, {
          fetcher: graphQLFetcher,
          defaultVariableEditorOpen: true,
        }),
        document.getElementById('graphiql'),
      );
    </script>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | App
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag 'application', defer: true
    = stylesheet_link_tag 'application', defer: true
    javascript:
      window.SENTRY_DSN = "#{ ENV['SENTRY_DSN'] }"
  body
    = yield

app/views/view/show.html.slim
doctype html
html
  head
    title
      | App
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag 'application', defer: true
    = stylesheet_link_tag 'application', defer: true
    javascript:
      window.SENTRY_DSN = "#{ ENV['SENTRY_DSN'] }"
  body.flex.justify-center